language: python
python:
  - "2.7"
  - "3.3"

branches:
  only:
    - master

install:
  - "pip install ."
  - "pip install -e .[testing]"  # for installing `tests_require`

script:
  - "./setup.py nosetests"
